  data:
    image: busybox:latest
    volumes:
      - /var/local/sentry/data:/data
      - /var/local/sentry/data/var/lib/postgresql/data:/var/lib/postgresql/data
    entrypoint: /bin/echo
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - sentry
    volumes:
      - "/home/arbitrio@fbk.eu/sentry-compose/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  sentry:
    build: .
    links:
     - redis
     - postgres
    env_file: ./secret_env_vars
    environment:
      - SENTRY_SERVER_EMAIL=arbitrio@fbk.eu
      - SENTRY_EMAIL_HOST=smtp.gmail.com
      - SENTRY_EMAIL_PORT=587
      - SENTRY_EMAIL_USER=arbitrio@fbk.eu
      - SENTRY_EMAIL_USE_TLS=yes
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
  celery.beat:
    build: .
    links:
     - redis
     - postgres
     - sentry
    env_file: ./secret_env_vars
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
    command: sentry celery beat
  celery.worker:
    build: .
    links:
     - redis
     - postgres
     - sentry
    env_file: ./secret_env_vars
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
    command: sentry celery worker
  redis:
    image: redis
    volumes_from:
      - data
    restart: always
  postgres:
    image: postgres
    volumes_from:
      - data
    restart: always
